!pip install numpy=2.5.0 pandas seaborn=3.0.0

In [4]:
import numpy as np 

In [5]:
temps = np.array([22, 24, 19, 21, 23, 25, 26]) #kathmandu temperature, mon-sun

In [6]:
type(temps)

numpy.ndarray

In [7]:
temps.ndim

1

In [8]:
temps.size

7

In [9]:
temps.shape

(7,)

In [10]:
temps.dtype

dtype('int64')

In [11]:
temps = np.array([22, 24, 19, 21, 23, 25, 26])

In [12]:
temps.dtype

dtype('int64')

In [ ]:
grid = np.array([
    [22, 24, 19, 21, 23, 25, 26], #kathmandu temperature 
    [37, 21, 32, 26, 24, 26, 28], # pokhara
    [37, 21, 32, 26, 24, 26, 28] # biratnagar
]) 

In [15]:
grid.shape

(2, 7)

In [16]:
grid.ndim

2

In [17]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.arange(2, 7)

array([2, 3, 4, 5, 6])

In [19]:
list(range(0, 9, 2))

[0, 2, 4, 6, 8]

In [21]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
# reshaping

In [24]:
flat = np.arange(1, 22)

In [23]:
flat.shape

(22,)

In [27]:
k = flat.reshape(3, 7)

In [31]:
k

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [30]:
k.ndim

2

In [28]:
k.size

21

In [29]:
k.shape

(3, 7)

In [ ]:


flat_one = np.arange(1, 13)

In [38]:
flat_one

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
k_one = flat_one.reshape(3, -1)

In [40]:
k_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
k.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
# indexing and slicing

# getting one value out of an array

# array[start:stop:step]

flat[2:4]

array([3, 4])

In [43]:
temps[1:6]

array([24, 19, 21, 23, 25])

In [44]:
temps[2]

np.int64(19)

In [45]:
temps[::-1]

array([26, 25, 23, 21, 19, 24, 22])

In [46]:
temps[:2]

array([22, 24])

In [47]:
# slicing a 2D grid: rows, columns, and blocks

grid[0, :]

array([22, 24, 19, 21, 23, 25, 26])

In [48]:
grid[:, 0]

array([22, 37])

In [55]:
# temperature of all cities for monday and tuesday:     monday -> sunday: monday -> index 0 and sunday -> index 6 

temperatures = np.array([
    [22, 24, 19, 21, 23, 25, 26], #kathmandu temperature 
    [37, 21, 32, 26, 24, 26, 28], # pokhara
    [37, 21, 32, 26, 24, 26, 28] # biratnagar
]) 

monday_tuesday_temps = temperatures[:, 0:2]

monday_tuesday_temps


array([[22, 24],
       [37, 21],
       [37, 21]])

In [56]:
# temperature greater than 25

grid > 25

array([[False, False, False, False, False, False,  True],
       [ True, False,  True,  True, False,  True,  True]])

In [57]:
grid[grid>25]

array([26, 37, 32, 26, 26, 28])

In [61]:
# views vs copies:what slicing actually returns
temps

array([22, 24, 19, 21, 23, 25, 26])

In [60]:
temps[2:6]

array([19, 21, 23, 25])

In [66]:
x = temps[2:6].copy()

In [67]:
x[2] = 30

In [68]:
x

array([19, 21, 30, 25])

In [69]:
temps

array([22, 24, 19, 21, 30, 25, 26])

In [ ]:
# vectorized operation
# applies the same calculations to every element at once


# why numpy is much faster
# - no need to check datatype
# - can add variable without list loop

# Broadcasting

import time
import numpy as np

# Create a list and an array with 10 million elements
size = 10_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

# 1. Pure Python Loop
start_time = time.time()
python_list_result = [x + 1 for x in python_list]
python_time = time.time() - start_time
print(f"Pure Python Time: {python_time:.5f} seconds")

# 2. Vectorized NumPy Operation
start_time = time.time()
numpy_array_result = numpy_array + 1
numpy_time = time.time() - start_time
print(f"NumPy Time: {numpy_time:.5f} seconds")

# Speedup factor
print(f"NumPy is {python_time / numpy_time:.1f}x faster!")

Pure Python Time: 1.07130 seconds
NumPy Time: 0.02666 seconds
NumPy is 40.2x faster!


In [74]:
grid

array([[22, 24, 19, 21, 23, 25, 26],
       [37, 21, 32, 26, 24, 26, 28]])

In [77]:
# what if the shapes don't match?

city_avg = grid.mean(axis = 1, keepdims=True)

In [78]:
city_avg

array([[22.85714286],
       [27.71428571]])

In [79]:
difference = grid - city_avg

In [80]:
difference

array([[-0.85714286,  1.14285714, -3.85714286, -1.85714286,  0.14285714,
         2.14285714,  3.14285714],
       [ 9.28571429, -6.71428571,  4.28571429, -1.71428571, -3.71428571,
        -1.71428571,  0.28571429]])

In [85]:
# matrix multiplication

a = np.array([2, 3, 1])
b = np.array([10, 10, 10])

In [84]:
# same element multiplication
a * b

array([20, 30, 10])

In [86]:
# dot multiplication

np.dot(a, b)

np.int64(60)

In [87]:
# axis just means which direction collapes

grid.min(axis = 0)

array([22, 21, 19, 21, 23, 25, 26])

In [88]:
# get the position of maximum temperature across city for each day

grid.argmin(axis = 0)

array([0, 1, 0, 0, 0, 0, 0])

In [89]:
grid.argmax(axis = 0)

array([1, 0, 1, 1, 1, 1, 1])

In [90]:
# random numbers

np.random.seed(42)

In [ ]:
np.random.rand(4) # 4 floats

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [93]:
np.random.randn(4)

array([-0.23415337, -0.23413696,  1.57921282,  0.76743473])

In [94]:
np.random.randint(0, 20, size=5)

array([ 1, 11,  5,  1,  0])

In [95]:
temps

array([22, 24, 19, 21, 30, 25, 26])

In [99]:
print(np.random.shuffle(temps))

None


In [100]:
temps

array([25, 30, 24, 26, 19, 21, 22])

In [102]:
# np.where is a vectorized if/else

label = np.where(temps > 24, "warm", "cool")
label

array(['warm', 'warm', 'cool', 'warm', 'cool', 'cool', 'cool'],
      dtype='<U4')

In [103]:
num = 2
"weekend" if num % 2 == 0 else "wekday"

'weekend'

In [105]:
# flipping an array, combining several into one

grid.shape

(2, 7)

In [ ]:
# transpose

grid.T.shape

(7, 2)

In [ ]:
# real data is messy 

np.unique(cities) #distinct values only
np.sort(temps) #values, smallest => largest
np.argsort(temps) #indices that would sort it
np.isnan(temps) # true/false per element
np.nanmean(temps) # mean, missing values ignored